#DOCKER INTERMEDIATE
FROM worsica/worsica-intermediate:development
MAINTAINER Ricardo Martins <rjmartins@lnec.pt>

COPY /repositories/worsica-intermediate /usr/local/worsica_web_intermediate
COPY /repositories/worsica-processing /usr/local/worsica_web_products

#set the path enviroment variable and the cwd
ENV PATH /usr/local/worsica_web-py363_venv/bin:${PATH}
WORKDIR /usr/local/worsica_web_intermediate


